name: openimis_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  change_app_package_name:
  get: 4.6.5
  flutter_typeahead: ^4.3.0
  google_fonts:
  flutter_screenutil: 5.9.3
  cached_network_image:
  image_picker:
  image_cropper:
  file_picker:
  qr_code_scanner: 1.0.0
  qr_flutter:
  local_auth: ^2.1.4
  sqflite: ^2.0.0+4
  path: ^1.8.0
  firebase_core:
  firebase_messaging:
  flutter_svg:
  lottie: 1.4.2
  carousel_slider: ^4.2.1
  flutter_markdown: 0.6.12
  persistent_bottom_nav_bar_v2: 4.2.5
  dio: 4.0.6
  get_it: 7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  intl:
  flutter_image_compress:
  otp_text_field:
  get_storage: 2.0.3
  heroicons:
  form_field_validator: 1.1.0
  intl_phone_field: 3.1.0
  shimmer: 2.0.0
  awesome_dialog:
  awesome_snackbar_content:
  country_codes: 2.2.0
  smooth_page_indicator: 1.0.0+2
  url_launcher:
  url_launcher_ios:
  flutter_svg_provider:
  expandable: 5.0.1
  khalti_flutter: ^3.0.0
  flutter_local_notifications:
  connectivity_plus: ^5.0.2
  webview_flutter: 3.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  flutter_native_splash: ^2.2.13
  logger: 1.1.0
#  device_preview:
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#03A9F4'
  color_dark: '#23A9F4'
  android_12: 
    color_dark: '#23A9F4'
  web: false

flutter: 
  assets: 
    - assets/
    - assets/translations.json
  uses-material-design: true

